### ISSUE TITLE
Run Soil ID algorithm on new input

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-backend#1095]
There is already another task for running the Soil ID algorithm when the site is created (#373). This task should cover the other times it needs to be run, such as when:

- a user selects a location on the map
- a user provides new slope/soil texture/soil color data

**Comment by DerekCaelin** [comment]
This issue is obsolete with [our new implementation plan.](https://tech-matters.slack.com/archives/C0376RCCXD2/p1714598343248489)
