### ISSUE TITLE
Build/retrieve list of possible soil names and ecological site IDs/names

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-backend#1097]
Designs may need updating, but this task involves:
- Building some sort of database with all of the possible US soil names (will need a different one for the international app)
- Build some sort of database with all of the possible ecological site IDs/names in the US.
- Build a mapping between the soil names and ecological site IDs/names, understanding that:
  - some soils have no ecological site ID/name match
  - some soils have multiple ecological site IDs/names

**Comment by DerekCaelin** [comment]
Closed as this is now a duplicate of:
- https://github.com/techmatters/terraso-product/issues/653
