### ISSUE TITLE
Add backend APIs for user deletion requests

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-backend#1112]
Backend work to allow users to send a request to delete their accounts. See parent issue for details. 

## References
- [Product Spec](https://docs.google.com/document/d/18t3V8KWm1wft7K66f91wwKfUQdwIQqJonFJszGaHGeM/edit#heading=h.b4eice3hjq0r)

## Acceptance Criteria 

- [ ] Write a script that allows staff members to complete deletion. Script should
  - [ ] delete the user account
     - [ ] delete unaffiliated sites
     - [ ] delete projects and affiliated sites where the user is the sole manager
  - [ ] Unsubscribe users from LandPKS mailing list https://app.hubspot.com/contacts/9151742/lists/16/filters
  - [ ] Use the hubspot template to inform the user their account has been deleted - [Delete Account Email Template](https://app.hubspot.com/templates/9151742)

**Comment by CourtneyLee333** [comment]
@paulschreiber I don't know how to test this one.
