### ISSUE TITLE
feat: set default values for soil project required inputs

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-backend#1197]
Set default inputs for projects to include soil texture), color, slope. Verify that this results in the desired behavior on the mobile clients by creating a new project and verifying that it has the correct settings for required inputs. could also do to add a test case for this!

## Acceptance Criteria
- By default, projects should turn toggles related to soil id, including:
   - soil texture,
   - soil color,
   - slope,
   - cracks 

Garo notes:
> `slope_required`, `soil_texture_required`, and `soil_color_required` fields of the `ProjectSoilSettings` model should all have their default value set to `True`.

**Comment by CourtneyLee333** [comment]
@DerekCaelin I don't want to change the acceptance criteria without your eyes on it, but I think:
- soil_pit_required is not an implemented feature, so shouldn't be on this list
- slope_required should include slope aspect and slope shape
- soil_texture_required should include texture class and rock fragment volume

**Comment by DerekCaelin** [comment]
Thanks - I've updated the criteria with product language.
