### ISSUE TITLE
debt: update measurement unit enum internal value from 'IMPERIAL' to 'ENGLISH'

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-backend#1212]
The UI says "English" now, less confusing if we make it consistent and it's an easy migration.

**Comment by ltseng** [comment]
Seeing a variable name show up instead of "Imperial" as well on the project settings page

![Screenshot_20240327-130440_Terraso LandPKS.jpg](https://github.com/techmatters/terraso-backend/assets/2730009/198db9d2-4e41-4ed3-884b-7236463440ed)
