### ISSUE TITLE
Can't log in with Microsoft Identity

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-backend#1242]
### App Version

1.0.110

### Platforms

- [X] iOS
- [X] Android
- [ ] iOS simulator
- [ ] Android emulator

### Description

User can't complete the process of logging in with Microsoft identity.  

### Steps to Reproduce

1. Open app, sign out of account
2. See the sign in screen
3. Select "Sign in with Microsoft"
4. Enter email address belonging to Microsoft account
5. See issue

### Expected behavior

User can type in password, proceed through microsoft login process, and return, signed in, to LandPKS. 

### Actual behavior

Error message:
```
We're unable to complete your request

invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.
```

### Additional context

https://github.com/techmatters/terraso-mobile-client/assets/10799815/8cc09ea2-7221-4ac3-8336-5b54ccb6db85

**Comment by paulschreiber** [comment]
This has been fixed. The old certificate expired. Updated the Azure dashboard and the Render configs with the new cert.
