### ISSUE TITLE
feat: improve login response time by not synchronously downloading and re-uploading the user's profile image on every login request

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-backend#1371]
## Description
I did some quick and dirty log statement profiling of the backend, and it seems that the vast majority of the time spent by the backend during a login request is synchronously downloading the user's profile image and uploading it to S3.

We should do at least one of:
- perform this profile image re-upload asynchronously
- only perform this profile image re-upload when the image has actually changed

Either method would resolve the slow login, but I'm not sure which is more straightforward to implement at first glance.

## Additional context
Specifically:
- all logins eventually hit [the `_persist_user` method](https://github.com/techmatters/terraso-backend/blob/edbf143be51a9908bcfbca1d1864fa86016c83de/terraso_backend/apps/auth/services.py#L99) of the `AccountService`
- If the login is associated with a profile image URL (which is always true for a google login), then we hit [the `_update_profile_image` method](https://github.com/techmatters/terraso-backend/blob/edbf143be51a9908bcfbca1d1864fa86016c83de/terraso_backend/apps/auth/services.py#L128)
- This then hits [the `upload_url` method](https://github.com/techmatters/terraso-backend/blob/8ac6f4ecaa8c9ebe44e59b9b3cca9e359d80e268/terraso_backend/apps/storage/services.py#L35-L49) of the `UploadService`, which downloads the file from the profile image URL, and then uploads it to S3
- I think it might also the case that a new file is uploaded to S3 each time, and the old files aren't cleaned up.

I don't have experience with launching async tasks in django, so not sure how big a lift that is. And I don't know if the profile image URL provides information to determine if it has changed or not. I'm not even sure if we need to be storing the profile images on our own backend or if we can just use the oauth provider's profile image URL as is.

**Comment by paulschreiber** [comment]
Some notes on background tasks:
https://agrahariyash.medium.com/asynchronous-task-queues-in-the-django-world-a5d9be407e18
https://realpython.com/asynchronous-tasks-with-django-and-celery/

**Comment by knipec** [comment]
Triage notes: 
- Context: we didn't know when someone changes their google profile picture, so we just got it every time. Not sure how to get notified when they change their picture. So sounds like there is a nontrivial amount of work
- We don't know if we need to clean up old ones? 
- Moving to a P2. This is annoying, but doesn't block functionality.
- Assigning to Jose to see if you have a proposed solution, otherwise wait til @shrouxm is back to refine this
- This would also speed up web client performance some as well

FYI @CourtneyLee333

**Comment by DerekCaelin** [comment]
Thanks, @josebui! - if it's alright I will put it in the August to-do list, with the expectation that it is a lower priority than the other tasks listed.

**Comment by paulschreiber** [comment]
This has been deployed to production.
