### ISSUE TITLE
Prototype - conflict-resolution server mutation for soil data

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-backend#1399]
implement a conflict-resolution server mutation, for soil data
- bulk ingest new soil data from client, internal backend state must be well-understood
- try 2 or 3 conflict-resolution policies under endpoint to understand each one's constraints
- consider cases: remote has newer data, remote site is deleted, remote permissions removed. how to signal to mobile app?
- consider persisting ingested inputs somewhere regardless of resolution outcome
- consider how to test

## References
[Offline Research](https://docs.google.com/presentation/d/1eHO52LqsSsOV6tyBQrEUA857VHsjGAdxQEDYWcWQLaY/edit#slide=id.g2f0a32b466d_0_47)
[Offline Workflows, Strategies, Scenarios (Mural)](https://app.mural.co/t/techmatters9109/m/techmatters9109/1718201688620/6fda9e75f14b7b3ca9aa614647d6cb278a8a4736?sender=u3faecbd439cadb255c696741)
[Offline User Stories](https://docs.google.com/document/d/1IkWYXugN1MtGxiWzadpaZ74UGlFb77eHu_8_PdREPRg/edit#heading=h.8gruape22iyw)

## Acceptance Criteria
- [ ] How would we break this down into smaller prototype chunks? (And create separate issues if appropriate)
- [ ] Presentation to the team
- [ ] Code branch with demo application

**Comment by shrouxm** [comment]
we discussed [this write-up](https://docs.google.com/document/d/1l8I_jbMno5FeuA4qgxuEh8bYgsoBt2sZo7SYSEqCxNQ/edit) from my research and came to a consensus on its conclusions so I'm marking this as done!
