### ISSUE TITLE
Duplicated slug error message doesn't follow the same pattern of other input errors

### ISSUE THREAD

**Issue by cacarrara** [techmatters/terraso-backend#147]
## Description
When creating a new Group with duplicated resulting slug, the API don't answer with the expected error structure implemented on this change: https://github.com/techmatters/terraso-backend/pull/115

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.

1. Go to URL: https://app.staging.terraso.org/groups/new
2. Enter "test" in the name field
3. Enter "test" in the description filed
4. Click "Save Changes"
5. See error:
![image](https://user-images.githubusercontent.com/348237/164519615-0e514cb6-f5f1-483f-bafe-8277a5e91229.png)

## Expected behavior
Duplicated slug errors should result in API messages following the same expected structure, as explained in https://github.com/techmatters/terraso-backend/pull/115

## Actual behavior
This is the current message being returned:
![image](https://user-images.githubusercontent.com/348237/164521674-7bd95005-ecd9-4d5a-9e3f-74dbdbc899f0.png)

**Comment by paulschreiber** [comment]
Web client issue: #291

**Comment by cacarrara** [comment]
Further clarification: the slug is originated from Group name. For name duplication, the validation and error message is working well. The problem will happen only when the Group name differs, but originates the same slug. For example, names "COBIOCOM" and "CoBiOCom" are different, but will create the same slug.

The nature of a slug is to be unique, so we cannot allow duplication. However, since we do soft-delete, our slug unique constraint only runs over non-deleted registers. This constraint is created directly on DB. So, when performing a save operation, this unique constraint will only be assessed on DB level, not on application level. The DB error message is the message being showed on the web client.

The PR will fix that.
