### ISSUE TITLE
Shared data files — S3 storage

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-backend#154]
## Description
* folder structure
* file names
* bucket access configuration

**Comment by paulschreiber** [comment]
I've created three S3 buckets
* files.terraso.org
* files.staging.terraso.org
* files.dev.terraso.org

I then added CNAMEs and certificates on Cloudflare.

**Comment by cacarrara** [comment]
We can close this issue, since the S3 related work is being done together with #152
