### ISSUE TITLE
Give specific error when uploads fail due to bad AWS credentials

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-backend#170]
## Description
Currently, if uploads fail due to bad AWS credentials, we see:
>Failed to upload the data file

We should show/log a more specific error indicating the problem.

**Comment by cacarrara** [comment]
We definitely shouldn't expose this level of detail on the API answer. The error message looks ok.

On the other side, on the logs, the stack trace is pretty explicit in both cases:

- Missing credentials raises and logs: `botocore.exceptions.NoCredentialsError: Unable to locate credentials"`
- Bad credentials raises and logs: `botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden"`

I'm not sure if there's something to do about that.

**Comment by shrouxm** [comment]
@paulschreiber do you still think this issue should be open given Caio's comment?
