### ISSUE TITLE
Some CSV files detected as text/plain and rejected

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-backend#171]
## Description
A clear and concise description of the problem.

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.

Create a file like so
```
hello,world
```

1. Go to URL: https://app.staging.terraso.org/groups/test3/upload
2. Click on select file
3. Attache the file described above
4. Click Upload FIles

## Expected behavior
File ies uploaded

## Actual behavior
Invalid file extension (.csv) for the file type text/plain

**Comment by cacarrara** [comment]
It only happens for small files that perhaps are impossible to properly classify as `csv`. It might be an extreme outlier.

Here we need to base our assessment on the formal definition of the CSV file:
```
1.  Each record is located on a separate line, delimited by a line
       break (CRLF).  For example:

       aaa,bbb,ccc CRLF
       zzz,yyy,xxx CRLF

   2.  The last record in the file may or may not have an ending line
       break.  For example:

       aaa,bbb,ccc CRLF
       zzz,yyy,xxx

   3.  There maybe an optional header line appearing as the first line
       of the file with the same format as normal record lines.  This
       header will contain names corresponding to the fields in the file
       and should contain the same number of fields as the records in
       the rest of the file (the presence or absence of the header line
       should be indicated via the optional "header" parameter of this
       MIME type).  For example:

       field_name,field_name,field_name CRLF
       aaa,bbb,ccc CRLF
       zzz,yyy,xxx CRLF
```
[ref](https://datatracker.ietf.org/doc/html/rfc4180#section-2)

From my tests (output below), a three line CSV  (probably the more realistic scenario) is already properly identified. Honestly, I don't think this is relevant work to worry at the moment. Definitely less than medium priority.

```python
In [1]: import magic

In [2]: magic.from_file('one_line.csv')
Out[2]: 'ASCII text'

In [3]: magic.from_file('two_line.csv')
Out[3]: 'ASCII text'

In [4]: magic.from_file('three_line.csv')
Out[4]: 'CSV text'
```

**Comment by DerekCaelin** [comment]
This issue appears to be happening again with files generated by KoBoToolbox. 

https://user-images.githubusercontent.com/10799815/194078508-f29fd210-c213-41ab-a400-55dfa3b9544f.mp4

[Bike_Facilities_in_Rocky_Hill_-_all_versions_-_labels_-_2022-10-05-13-54-07.csv](https://github.com/techmatters/terraso-backend/files/9716202/Bike_Facilities_in_Rocky_Hill_-_all_versions_-_labels_-_2022-10-05-13-54-07.csv)
