### ISSUE TITLE
Terraso - KoboToolbox integration

### ISSUE THREAD

**Issue by caiocarrara** [techmatters/terraso-backend#26]
## Description
KoboToolbox is a platform for data collection on field, focused for data collection in challenging environments. It's a goal from Terraso product team to offer a version of KoboToolbox hosted by ourselves and somehow integrated with the rest of Terraso ecosystem.

The initial and most eminent form of integration would be integrating accounts. So, users already registered on Terraso don't need to create and manage new accounts on KoboToolbox.

The other possible integration would be for two-ways data exchanging between the two platforms. Both to have Terraso data on KoboToolbox (Groups, for example), and also to have KoboToolbox data on Terraso (survey data, for example).

## Resources
- [KoboToolbox](https://www.kobotoolbox.org/)
- [KoboToolbox GH](https://github.com/kobotoolbox/)

## Suggested Subtasks
- [x] Review KoboToolbox architecture
- [x] Specify KoboToolbox infrastructure requirements for _Terraso deployment_
- [x] Implement some sort of KoboToolbox automated deployment
- [x] Design KoboToolbox → Terraso integration and schedule
- [x] Design KoboToolbox support for third-party authentication (OAuth)
- [x] Design Terraso changes to make it work as a OAuth provider (if integration with KoboToolbox be through OAuth)
- [x] Implement KoboToolbox changes and submit it to upstream
- [ ] Implement Terraso changes

### User Stories Acceptance Criteria
- [ ] As a Terraso user, I want to be able to navigate to the KoBo Toolbox login screen from the Terraso toolbox, where I find tools relevant for landscape management
- [ ] As a Terraso user _without_ a Kobo account, I want to be able to use my Terraso identity to create an account with KoBo Toolbox, so I don't need to memorize yet another password
- [ ] As a Terraso user _with_ a Kobo account, I want to log in with my Terraso identity and start collecting data.

## Design
- [ ] Implementation matches design
- [ ] Copy Editing
- [ ] Translation (Spanish)
- [ ] Additional changes...

## Not blockers - next sprint?
- [ ] Terraso authorization screen needs an update [to match design](https://www.figma.com/file/TCnUik1BcW0KIhu9hK60WO/SSO-KoBoToolbox?type=design&node-id=3-15&t=GKlVRi3hTA736Cft-0).

**Comment by DerekCaelin** [comment]
@david-code if you haven't, would you reach out to the KoBo team and ask if our proposed solution to auto-fill their form is acceptable?

**Comment by david-code** [comment]
> @david-code if you haven't, would you reach out to the KoBo team and ask if our proposed solution to auto-fill their form is acceptable?

@DerekCaelin I haven't done this yet. I'll make an issue outlining the proposed solution on the KoBo repo and let their team know about it.

**Comment by david-code** [comment]
[Skip signup form issue](https://github.com/kobotoolbox/kpi/issues/4353) created.

**Comment by david-code** [comment]
[Template messaging PR](https://github.com/kobotoolbox/kpi/pull/4391)

**Comment by david-code** [comment]
PR is expected to go live on KoBo main instance next week. I will check back then.

**Comment by DerekCaelin** [comment]
Thanks, David. Great to hear.
