### ISSUE TITLE
Missing CSS and JS files in "static" S3 bucket

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-backend#279]
## Description
Missing CSS and JS files in "static" S3 bucket

On production, when accessing the admin console, we get these errors:
```
GET https://static.terraso.org/admin/css/dark_mode.css net::ERR_ABORTED 403
GET https://static.terraso.org/instance_restore.js net::ERR_ABORTED 403
```

Staging and testing have `dark_mode.css` but not `instance_restore.js`.

1. Add `dark_mode.css` to production
2. Move `instance_restore.js` to `js` subfolder.
3. Add `instance_restore.js` to all environments.

**Comment by david-code** [comment]
This issue was resolved by running the `mange.py collectstatic` command.
