### ISSUE TITLE
Figure out how group creation, landscapes and users work in Terraso. Present a plan to how to split this out into separate interfaces that can be reused with LandPKS

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-backend#320]

**Comment by JeancarloBarrios** [comment]
So anyone can see the document as I advance on this 
https://hackmd.io/@dI3EQ6hcTwaUdWO7N8TL9g/B174E6hk2

**Comment by shrouxm** [comment]
i can't figure out how to leave comments on that document, but it would be helpful to have some code snippets to explain how the proposed architecture will differ from the current one in practice. i have so little django experience i'm finding it hard to visualize concretely

**Comment by JeancarloBarrios** [comment]
Sure I will add them, i think i like how protocol works so will make an example
