### ISSUE TITLE
Append to Site AuditLog on Site Creation

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#336]
# Description

Here is an example of the AuditLog that should be created on Site creation.

```
November 12, 2023 12:41:43 GMT - Maria de la Vega created site at 40.826280,-98.613164
November 12, 2023 12:41:43 GMT - Maria de la Vega named site “My Test Site”
November 12, 2023 12:41:43 GMT - Maria de la Vega set “My Test Site” as private
```

This issue is to brainstorm how these logs should be stored and implement

# Requirements

- Brainstorm how these logs should be stored. We don't want to store the entire text, but we need to be able to recreate the text above from whatever is stored.
- Present possible solutions to engineering team for feedback.

**Comment by shrouxm** [comment]
writing down possible schema while it's in my head:
```
event_id  (PK)  |  {site, project}_id   (FK)  | event_time | user_id   (FK)  |  event_data
```
where `event_data` is a json blob with a mandatory `type` field and then all other fields depend on `type`, egs:
```
{'type': 'site_creation', 'location': {'lat': 40.826, 'lon': -98.613}, 'site_id': '...'}
{'type': 'site_privacy', 'private': True}
```

**Comment by ltseng** [comment]
This has been in progress for the last month and a half (minus one week in blocked). What's the status of this task?

**Comment by ltseng** [comment]
@JeancarloBarrios Is this task safe to close?
