### ISSUE TITLE
Audit Logs Architecture

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#340]
# Description

This task will be to sketch out the architecture for Audit Logs.

[Sample audit log for discussion](https://docs.google.com/document/d/1LGogXepXyGoyuddtgkwaeTFN-bvdKrhFE8hKjSopmmI/edit#)

**Comment by ltseng** [comment]
Is this still a valid task? @JeancarloBarrios

**Comment by JeancarloBarrios** [comment]
This tasks could be considered done
