### ISSUE TITLE
Site-User-Project Architecture

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#371]
# Description

We know that when a User creates a Site, that Site needs to be linked to the creating User. There are several ways of implementing this. This issue is to brainstorm different implementations and decide on a way forward.

# Definition of Done

- [ ] Architecture outlined in comments to this issue
- [ ] Reviewed and approved by team members

**Comment by david-code** [comment]
<div id="content">
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#org9f24be5">1. Introduction</a></li>
<li><a href="#org1261be4">2. Site creation</a></li>
<li><a href="#orgff82553">3. Moving sites between projects</a></li>
<li><a href="#org14b5fa5">4. Adding users to projects</a></li>
<li><a href="#org0e8fe21">5. Viewing sites</a></li>
<li><a href="#orgd47c886">6. Implementation</a></li>
</ul>
</div>
</div>
<div id="outline-container-org9f24be5" class="outline-2">
<h2 id="org9f24be5"><span class="section-number-2">1</span> Introduction</h2>
<div class="outline-text-2" id="text-1">
<p>
This document outlines the requirements for the interaction of sites, users and projects. It also documents how we will use a "personal" project to fulfill these requirements. It is not a complete description of project role privileges &#x2013; see the Project Management spec for more details.
</p>
</div>
</div>

<div id="outline-container-org1261be4" class="outline-2">
<h2 id="org1261be4"><span class="section-number-2">2</span> Site creation</h2>
<div class="outline-text-2" id="text-2">
<p>
When User A creates a site, and user A doesn't belong to any projects, the site will be added automatically to the user's "personal" project.
</p>


<div class="figure">
<p>
<img src="https://user-images.githubusercontent.com/18663493/231857237-50807051-8fb1-4f1c-b618-67baf0212966.png">
</p>
</div>

<p>
A personal project is the same as any other project in most aspects, but with a few additional restrictions.
</p>

<p>
If User A belongs to multiple projects, the user can add the site to a specific project. In the next diagram, the user has joined OtherProject, and adds Site2 to that project.
</p>


<div class="figure">
<p>
<img src="https://user-images.githubusercontent.com/18663493/231857311-2238d18f-9fb9-4232-8bcb-2bcaeca072b6.png">
</p>
</div>

<p>
If UserA creates a Site3, and does not choose to add it to OtherProject, Site3 will still be added to UserProject.
</p>


<div class="figure">
<p>
<img src="https://user-images.githubusercontent.com/18663493/231857471-cab720b0-cdb0-44c4-965b-ba19ff6a6752.png">
</p>
</div>
</div>
</div>
<div id="outline-container-orgff82553" class="outline-2">
<h2 id="orgff82553"><span class="section-number-2">3</span> Moving sites between projects</h2>
<div class="outline-text-2" id="text-3">
<p>
User A can move any sites from their "personal" project to any other project to which they belong.
</p>

<p>
If User A is a member of Project B, and Project B allows members to edit the project's sites, UserA can move sites to another project.
</p>

<p>
If User A is a manager of Project B, User A can move sites to another project, regardless of the settings on editing sites.
</p>

<p>
If User A is a member of Project B, and Project B does not allow members to edit sites, User A cannot move sites in Project B to another project. For example, in the following example User A cannot move any sites for Project B.
</p>
</div>
</div>

<div id="outline-container-org14b5fa5" class="outline-2">
<h2 id="org14b5fa5"><span class="section-number-2">4</span> Adding users to projects</h2>
<div class="outline-text-2" id="text-4">
<p>
Unlike adding sites to a project, only managers can invite new members to a project, choose to grant them manager privileges, and remove them.
</p>

<p>
Users cannot be added to a personal project, as we want to respect the specification that sites not added to a project are not visible to other users.
</p>
</div>
</div>

<div id="outline-container-org0e8fe21" class="outline-2">
<h2 id="org0e8fe21"><span class="section-number-2">5</span> Viewing sites</h2>
<div class="outline-text-2" id="text-5">
<p>
Users can view sites in their personal projects.
</p>

<p>
They can also view projects.
</p>

<p>
Sites in public projects can be viewed by anyone. Sites in private publics are only visible to their members.
</p>

<p>
Sites in a personal project should only be visible to the associated user. As such, personal projects should be treated as private projects. It shouldn't be possible to make a personal project public.
</p>
</div>
</div>

<div id="outline-container-orgd47c886" class="outline-2">
<h2 id="orgd47c886"><span class="section-number-2">6</span> Implementation</h2>
<div class="outline-text-2" id="text-6">
<p>
A personal project is essentially the same as other projects, with the following restrictions:
</p>

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Category</th>
<th scope="col" class="org-left">Normal</th>
<th scope="col" class="org-left">Personal</th>
</tr>
</thead>
<tbody>
<tr>
<td class="org-left">Adding members</td>
<td class="org-left">Manager</td>
<td class="org-left">Not allowed</td>
</tr>

<tr>
<td class="org-left">Public view of sites</td>
<td class="org-left">Setting</td>
<td class="org-left">Not allowed</td>
</tr>
</tbody>
</table>

<p>
Adding a personal project for each user should allow us to follow the specifications, as long as the above restrictions are respected. The restrictions should be enforced on the backend.
</p>
</div>
</div>
</div>
<div id="postamble" class="status">
<p class="author">Author: David Howard</p>
<p class="date">Created: 2023-04-13 Thu 14:52</p>
</div>

**Comment by david-code** [comment]
@shrouxm @JeancarloBarrios Trying something new here. I wrote up some architecture discussions in an [org-mode](https://orgmode.org/worg/org-syntax.html) file with [plantuml](https://plantuml.com/) diagrams. I was thinking that comments could be made just through quote replies. Could you take a look and see if it makes sense to you?

**Comment by shrouxm** [comment]
well those diagrams are pretty nifty! i am happy to discuss this way, especially for async conversations. it might get a bit unwieldy for really long conversations, but on the other hand it is nice to have a linear record of the decision making process!

re the actual architecture proposal: that makes sense and i would be happy with it. 

the alternative i see is allow a site to be owned by a project _or_ a user, which would be implemented by the `site` model having a nullable `owner_user` and `owner_project` field, FKs to the respective tables, and checks to ensure that exactly one is not null at all times. 

this is closer to the user's model of what is going on, but given the languages we are implementing in i think it might be a bit more finnicky to make work, although they both seem like they'll have finnicky aspects.

i am leaning towards your proposal but curious to hear thoughts!

**Comment by shrouxm** [comment]
I think we agreed this is done during team meeting so I am closing the issue.
