### ISSUE TITLE
Create data schema for site measurements

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-backend#381]

**Comment by ltseng** [comment]
I created this issue for now, but since the site measurements themselves are something we won't get to until Q3, I wonder if the data schema for site measurements is something that we can even begin to start working on right now.

@paulschreiber @shrouxm @david-code @JeancarloBarrios

**Comment by david-code** [comment]
> I created this issue for now, but since the site measurements themselves are something we won't get to until Q3, I wonder if the data schema for site measurements is something that we can even begin to start working on right now.
> 
> @paulschreiber @shrouxm @david-code @JeancarloBarrios

Agreed, it seems premature to start working on this.

**Comment by shrouxm** [comment]
Closing this issue because I didn't see it til after I already fleshed out another issue for the same thing.
