### ISSUE TITLE
Email notification has broken/missing image for Terraso logo

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-backend#396]
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/10799815/229616812-0b2bb6ce-d810-4fed-9053-e92a6dee51c8.png">

## Description
The terraso logo does not appear in the email notification that came from Teraso. 

## Steps To Reproduce

1. Manager: create closed group
2. User: request to join closed group
3. Manager: check email
4. Manager: read email contents

## Expected behavior
Display the Terraso logo

## Actual behavior
The Terraso logo fails to load - only alt-text is seen.

**Comment by paulschreiber** [comment]
This is fixed and deployed to staging.

**Comment by DerekCaelin** [comment]
Confirmed and thank you.
