### ISSUE TITLE
Personal sites can be created

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#455]
# Description

Sites that a user creates and that are not added to a named project will be treated as personal sites. From there, the user can manipulate them as a manager could if a site were added to a project.

# Design
![db_schema](https://user-images.githubusercontent.com/18663493/234322939-a9990c25-4dc1-49d6-bb6f-047dfbaf31dc.png)

Originally I planned to make the personal sites belong to a personal project. This project would be private, and the settings could not be edited. However, thinking a bit further about this, it is a bit clunky. For example, we need to enforce a constraint on the groups related to the personal projects only having one member, not being deleted, etc. Also the project settings will not make any sense for a private project.

As an alternative, I think it makes sense to associate sites not to a project, but to a site collection (name not decided yet). The idea would be to use the Django ORM inheritance options to have two different models, PersonalSites and ProjectSites that inherit from the model. In SQL, this would mean two different nullable foreign keys with a constraint that one must be not null, I think. ProjectSites would link to a project, while PersonalSites would link to a user. This makes it easier to enforce some constraints (only a single user, no project settings, etc.) with the caveat that it will make checking permissions slightly more clumsy.

# Defintion of Done

- [ ] Other users cannot be added to gain access of these personal sites
- [ ] User can edit and update personal sites

**Comment by david-code** [comment]
@JeancarloBarrios @shrouxm Could you look this over and let me know what you think?

**Comment by david-code** [comment]
New complication: need to consider that sites belonging to personal projects can be shared with other users.

**Comment by JeancarloBarrios** [comment]
@david-code How exactly does Django manage inheritance regarding tables?
