### ISSUE TITLE
Split the group model into MembershipList and Group

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#457]
## Plan

- [x] https://github.com/techmatters/terraso-backend/issues/790
- [x] https://github.com/techmatters/terraso-client-shared/issues/93
- [x] https://github.com/techmatters/terraso-mobile-client/issues/410

**Comment by ltseng** [comment]
If this task is no longer valid, can we close it out?

**Comment by david-code** [comment]
It is still valid, but we won't do it right away I think.

**Comment by ltseng** [comment]
Jose has done some work for this, so we will need to revise the size estimate and break down into further subissues as necessary @shrouxm

**Comment by david-code** [comment]
@ltseng fyi the work Jose has done will take care of most of this issue. I'm going to update the description to describe the remaining work to do.

**Comment by ltseng** [comment]
Is there an engineering size associated with this? (Don't want to throw you off your work too much otherwise)

**Comment by david-code** [comment]
@ltseng I'm not sure how to best handle this, I assigned engineering to the sub-tasks I listed in the description instead of this issue.

**Comment by ltseng** [comment]
I keep forgetting to check for sizes on the subissues 😅 ignore me!
