### ISSUE TITLE
Discussion: Viewer, Contributor and Manager roles for Projects

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#529]
# Overview

We have received a request to estimate how much effort would be needed to incorporate the roles of Viewer, Contributor and Manager into LandPKS Projects. This issue will outline potential solutions.

# Terms

I'm going to use the word "Community" to refer to Terraso Groups, Projects and Landscapes. It's a temporary term just relevant for this issue. UserGroup is used to describe the proposed separate table uniting all three.

# Background

Currently Users belong to UserGroups through a many-to-many relationship, mapped through the Membership model. We differentiate the role of a User in the group by the role property of the Membership.

# Problems

- Because the Membership is linked directly to a UsergroupGroup, without knowing anything about what type of Community this Group is used by, it is difficult to provide different roles directly through a Membership. As an example, if a UserGroup is used by a Project, we would like the roles to be Viewer, Contributor and Manager. However, for a Terraso landscape, we only want members and managers.

# Solutions

1. The easiest solution would be to commit that all Terraso Communities share a common set of roles: Viewer, Contributor and Manager. 
    - Implementation here would be trivial, but it would be the least flexible option. It doesn't allow for Communities to develop different roles. This could become problematic because different Communities need to control access to different objects. For example, it might be necessary to make a role for Projects that deals with a specific feature of Sites (although in reality, we will probably want to avoid such a specific role).

3. A more complicated solution:

![diagram](https://github.com/techmatters/terraso-backend/assets/18663493/ec0a156b-a360-43f2-b750-ccf1435e963b)

  The core "usergroup" table can be thought of a kind of abstract class. It is [extended](https://docs.djangoproject.com/en/4.2/topics/db/models/#multi-table-inheritance) by concrete child classes (`simple_usergroup`, `base_usergroup`). Users belong to these groups through specific memberships, which can define the role the user has in the respective group.
- Benefits:
    - Very easy to create a new type of group
    - UserGroup capabilities can be removed from the database. Right now what we're planning to do is store group capabilities in columns in the User group itself, like for example "user_can_join". This solution, where groups are effectively typed, will allow us to remove these from the database and deal with it in application code. This is more flexible (can change a few lines of code rather than running a migration) and less prone to programming errors (with storing capabilities in the DB, for example, difficult to enforce that all SimpleGroups need a user to join).
- Drawbacks:
   - Added complexity. No way around this, this definitely adds complexity to our implementation.
   - Strict correctness is weakened because CHECK constraints only operate on a single table. In practice, it is easy to prevent programming mistakes because the unique primary key is shared between tables, so it's impossible to create two different child UserGroups belonging to different tables with the same parent UserGroup. However, it would be possible for someone running SQL queries against the database to get two child UserGroups to point to the same parent UserGroup, for example. This can be prevented through triggers, but probably not worth the effort.
   - Would require changes to the GraphQL mutations to join groups, edit groups, etc.

# Questions

- There must be other solutions as well. Is there a compromise solution that would allow us to retain more flexibility than the first, without the complexity of the second?

**Comment by shrouxm** [comment]
i'm going to dive into this, but some initial questions: 
- we discussed [here](https://tech-matters.slack.com/archives/C02K02L3Q48/p1684890483903489) using the name `MembershipList` for what you're calling `UserGroup`, and i've started using that terminology in https://github.com/techmatters/terraso-web-client/pull/966, could we use that here as well? i've been finding it very helpful for parsing this
- could we include as part of this discussion a description of what the GraphQL API surface will look like for the different cases? or will it be the same? i'm not clear on if this is a proposal for how best to manage just the DB code or also how to present the API to clients
- how do you see this change in relation to https://github.com/techmatters/terraso-backend/issues/457, does this supersede it? would it be helpful to do that first change before diving into this?

**Comment by shrouxm** [comment]
ok a couple compromise solutions which exist in between the space of simplicity/flexibility of the original propositions:

## more flexible compromise
the reason to have shared roles between different communities is to not have to reimplement permissions code around joining/leaving groups & modifying other users' memberships. right now we are then also overloading those roles to also represent permissions to edit the communities' data. so what if we separate those concerns, and we get a compromise model like the following:
```
    Project            Group            Landscape
              \1-1       |1-1         /1-1
               \         |           /
                   MembershipList (open, closed) (invitations_allowed)
                         |1-many
              1-1        |
ProjectRole   ---   Membership (member, admin)
(viewer,                 |1-many
contributor)             |
                       User
```

& another thought: 

## more simple compromise
so far it seems the only concepts of different roles we've discussed are around ability to edit the membershiplist itself and permissions to edit the associated communities' data. can we parse those out into separate enums on `membership`, knowing that some types of communities won't use every possible kind of enum? can we add a constraint for each community to make sure the enums are in valid states for those communities? so `membership` would have columns for: `membership_role: MANAGER | MEMBER`, `data_role: EDITOR | VIEWER`. then we have LandPKS Manager is `(MANAGER, EDITOR)`, contributor is `(MEMBER, EDITOR)`, and viewer is `(MEMBER, VIEWER)`. i believe the way landscapes and groups work right now is they would have two role combos, `(MANAGER, EDITOR)` and `(MEMBER, EDITOR)`.

**Comment by shrouxm** [comment]
ok, & one more thought about exposing things in the GraphQL API:
- one view we could expose is where client isn't concerned about any of this. a `ProjectNode` would have a `members: ProjectMemberConnection!` field, and `ProjectMemberNode` would have `user: UserNode!, role: ProjectRole!`. there would be an `addProjectMember`, `removeProjectMember`, and `updateProjectMember` mutation. and all the same would exist for `Landscape` and `Group`. this would be a bigger change from how the client currently works
- the other view would be that `ProjectNode` contains a `MembershipListNode`, which contains a `MembershipConnection`. unclear how this would work flexibly with different role sets for different communities. perhaps using GraphQL interfaces? this is closer to how the client currently works

i think in a vacuum the first approach sounds better, it encapsulates the abstraction earlier in the dependency chain, but i'm not clear on the extra effort to get the clients to work with that approach. i.e. we need to have code somewhere which translates the semantic logic of the community into the data logic of the backend, and since the backend is already aware of that semantic logic we might as well do the translation in the backend so the client doesn't even have to think about it

**Comment by david-code** [comment]
> could we include as part of this discussion a description of what the GraphQL API surface will look like for the different cases? or will it be the same? i'm not clear on if this is a proposal for how best to manage just the DB code or also how to present the API to clients

Yes, let's take a look at this as well. I was just thinking in terms of the data schema, but that's relevant too.

> how do you see this change in relation to https://github.com/techmatters/terraso-backend/issues/457, does this supersede it? would it be helpful to do that first change before diving into this?

Definitely related. I think it depends on the solution we go with. The one you proposed wouldn't need to to do #457 first, but it would be necessary if we do the one I proposed first.


As to the data scheme, these are some good points. I like the more flexible approach you proposed in the first comment. Here's some code that would show how we could handle it for a GraphQL mutation to add someone to a membership list. (Note that this would be a solution where we don't create separate mutations for adding a user to a project, but basically what we're currently doing).

```python
 @classmethod
 def mutate_and_get_payload(cls, info, member_list_id, member_id, role_id):
     member_list = get_member_list(member_list_id)
     member = get_member(member_id)
     role = get_role(role_id)
     if not member_list.is_manager(info.context.user):
         raise not_allowed()
     if role not in member_list.allowed_roles:
         raise bad_request()
     membership = Membership.objects.create(member_list=member_list, member=member, r
 ole=role)
     return AddMembershipMutation(membership=membership)
```

You can see that the code works by checking:
1) if the user is a manager of the member list
2) checking if the role of the new membership makes sense with the membership list

I think this would be a good solution for our current use case, easy to implement and very flexible. It would get maybe a bit messy if we had a lot of different kinds of roles, but I don't think that's a drawback: for now at least, I expect our membership roles to be quite simple.

I think it would be better to go for the more flexible solution (storing roles in a separate table) rather than the simpler one; it is not much harder to implement and I think easier to accommodate new  types of memberships in the future.

As to the GraphQL API: I think it might make sense to just go for the second solution first. I am a bit conflicted about the first approach - it seems clearly a better idea for the frontend code not to know about MembershipLists at all, and I'd like to use that in the new code we're writing for LandPKS. However I also don't want to work on changing the 1000L client code too much, as we have plenty of thing to do on the LandPKS side. My ideal solution would be to do 2) with the new LandPKS code, "deprecate" manipulating memberships directly from the front end, and setup the refactoring needed for 1) in a future 1000L sprint. I think this is something we should definitely talk about with Jose when we've come to a decision.

On a kind of meta level, it would be good to develop a kind of guideline for how to approach differences with the currently existing 1000L code that we might want to refactor.

Recap:
- Like the approach of storing roles in a separate table, leaning strongly
- Preference for not refactoring the 1000L client code right away

**Comment by shrouxm** [comment]
ok i think we're on the same page then:
- communities that need extra roles can create a table with an FK to the membership table
- projects will present a GraphQL view/mutations that encapsulate the implementation details of the membershiplist/roles tables
- we will maybe create a backlog issue to encapsulate groups/landscapes in the same way

some positive notes about this:
- storing roles in a separate table is backwards compatible with the current backend approach, and i think orthogonal to the other groups refactor
- migrating groups/landscapes can be gradual if we want (we could gradually create the desired GraphQL views/mutations on the backend without removing the current ones, then migrate the client code gradually, then remove the deprecated GraphQL endpoints)

**Comment by shrouxm** [comment]
also here is how it would look if we do it before the other group migration:
```
              Project     Landscape
                  \1-1       /1-many
                    \       /
                      Group (open, closed) (invitations_allowed)
                         |1-many
              1-1        |
ProjectRole   ---   Membership (member, admin)
(viewer,                 |1-many
contributor)             |
                       User
```

**Comment by shrouxm** [comment]
closing since discussion is resolved & implementation issue created
