### ISSUE TITLE
testing: create unit tests for GraphQL mutations

### ISSUE THREAD

**Issue by shrouxm** [techmatters/terraso-backend#547]
## Description
Currently we only have unit tests for GraphQL queries in our backend. We should also test mutations. 

## Additional context
See https://github.com/techmatters/terraso-backend/blob/e255b8fd6eae9511f332e5de5556c072d9ffe645/terraso_backend/tests/graphql/conftest.py for where we create fixtures to run GraphQL queries. We will need to create fixtures to run mutations as well, & then create tests using those fixtures.

**Comment by david-code** [comment]
@shrouxm There is a subfolder with mutation tests: https://github.com/techmatters/terraso-backend/tree/e255b8fd6eae9511f332e5de5556c072d9ffe645/terraso_backend/tests/graphql/mutations

**Comment by shrouxm** [comment]
oh i see they are in a separate folder, i missed that, thank you!
