### ISSUE TITLE
Allow changing user role in backend GraphQL query

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#563]

**Comment by shrouxm** [comment]
@david-code similar question to here: https://github.com/techmatters/terraso-backend/issues/564#issuecomment-1597839550

**Comment by ltseng** [comment]
Also here @david-code :)

**Comment by ltseng** [comment]
If this is a valid task, please assign a size to it too!

**Comment by david-code** [comment]
Same as other issue.
