### ISSUE TITLE
Update GraphQL Mutation for removing User  from Group (MemberList) to match LandPKS needs

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#564]

**Comment by shrouxm** [comment]
@david-code what needs to change about the existing GraphQL mutation for LPKS? also my understanding was we were planning to create `{add,remove,update}ProjectMembership` mutations that hide the implementation details of member lists from the client, does that make this issue irrelevant?

**Comment by ltseng** [comment]
@david-code can you figure out what's going on here?

**Comment by ltseng** [comment]
If this is a valid task, please assign a size to it too!

**Comment by david-code** [comment]
Work has already been completed. @shrouxm Yes, that is the plan. There is no issue for this as of now. I would say this is more technical debt though, not necessarily linked to the same user story.
