### ISSUE TITLE
Track if projects and sites have been seen by user

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#672]
In order to keep track if a user has seen a given project or site we need to update the DB schema and GraphQL methods.

Proposed implementation: 
- many to many mapping between users and sites/projects
- row added when user added to project / new site is created in project in which the user is a member
- row deleted by frontend when user sees the object

**Comment by shrouxm** [comment]
@ltseng  i just finished the backend work for this as it is marked high priority for this milestone, and went to file additional issues for the client API and UI work but then noticed it is tracked by the polishing up the app user story https://github.com/techmatters/terraso-product/issues/317 which says it is low priority. should i be working on this right now?

**Comment by ltseng** [comment]
It's fine that you did it now,  it helps us move one step closer to finishing projects up for good!
