### ISSUE TITLE
Broken links for Altiplano Estepario, uMngeni, COBIOCOM

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-backend#68]
## Description

* Altiplano Estepario: https://www.commonland.com/landscapes/the-starting-point-is-inspiration-proving-change-is-possible/
* uMngeni: http://biodiversityadvisor.sanbi.org/participation/umngeni-ecological-infrastructure-partnership/
* COBIOCOM: https://twitter.com/cobiocom

- [x] Update AIrtable
- [x] Update sample data
- [x] Update production
- [x] Update staging
- [x] email sanbi.org and tell them to fix their server to support HTTPS

**Comment by cacarrara** [comment]
For Altiplano Estepario Steve said on Slack:

> I just came up with a suggestion because what was there wasn't working.  I'm not picky!

The current URL is working again. We cannot be responsible for external resources. Derek added:

> I assume the landscape leaders will eventually pick the best link to represent them
