### ISSUE TITLE
Group management API changes

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-backend#70]
## Description

Changes needed:
- [x] Make the Group creator automatically have the Manager role;
- [x] Allow only Group Managers to update their groups;
- [x] Create / adapt API to Group Managers remove members;
- [x] Do not allow empty Groups. A Group always need to have at least one Manager;

Web client issue: https://github.com/techmatters/terraso-web-client/issues/97

**Comment by cacarrara** [comment]
Regarding:

> Create / adapt API to Group Managers remove members;

We already have a GraphQL mutation to perform this operation: `deleteMembership()`. The PR #95 adds the proper permission checks before deleting a `Membership`.
