### ISSUE TITLE
Story maps: incorrect text in invite email

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/terraso-backend#794]
## Description
Incorrect text in the story map invite email:

<img width="735" alt="image" src="https://github.com/techmatters/terraso-backend/assets/86784/3fb57394-fa30-4d2b-a5aa-0a5a8a476bbd">

* button has i18n key instead of text
* header: recipient's email is listed instead of sender's name

**Comment by DerekCaelin** [comment]
This appears to be resolved!
