### ISSUE TITLE
Make ProjectMembershipNode user required

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#859]
Currently the base `MembershipNode` has an optional `user` field, as anonymous memberships can be created for Story Maps while the user has not confirmed their email. However anonymous memberships don't make any sense for our case. We should be able to at least manipulate the GraphQL type so that the `ProjectMembershipNode` user is required.

**Comment by shrouxm** [comment]
closing as this has gotten resolved at some point, not sure when
