### ISSUE TITLE
User query by project includes deleted memberships

### ISSUE THREAD

**Issue by david-code** [techmatters/terraso-backend#870]
I was testing out the add user to project screen and I noticed that the memberships I deleted manually from the Django admin were still being accounted for in the query. It seems like perhaps the safe delete Object Manager is being ignored.

note (garo): i tagged good first issue because i think it might be a great way to learn some of the thornier parts of django, but for someone with no django experience might be more of a "good first issue to pair on" than a "quick fix to get your feet wet". maybe "good first issue" isn't a great tag name, since definitionally any contributor could only do one such issue 🤔

**Comment by david-code** [comment]
Another problem: The query matches an empty string for email, which is puzzling. Maybe it matches the current user sending the request?

**Comment by david-code** [comment]
Changed the title so this just focuses on matching empty email query string

**Comment by DerekCaelin** [comment]
I've [asked engineers if this is an issue](https://tech-matters.slack.com/archives/C02K02L3Q48/p1718211889029349) and nobody seems to encounter it now. Closing (with the expectation that we can reopen if it's actually a thing)
