### ISSUE TITLE
User data updated with provider information on every login

### ISSUE THREAD

**Issue by josebui** [techmatters/terraso-backend#89]
## Description
Every time the user logs in the information for the user is overriden

## Steps To Reproduce
Steps to reproduce the behavior. Describe what you typed, clicked, tapped, swiped, saw and heard.
1. Update data of a user names thorugh the Graph QL interface
2. Login to terraso web client
3. See how the names are updated

## Expected behavior
Updated names should be kept, and provider information should only be used when there is no data

## Actual behavior
User names are overriden every time the user logs in

**Comment by cacarrara** [comment]
@josebui yesterday I opened this PR that maybe fix this issue:

- https://github.com/techmatters/terraso-backend/pull/88

**Comment by josebui** [comment]
Closing because fixed in https://github.com/techmatters/terraso-backend/pull/88
